<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- Datos de vuestro grupo -->
    <groupId>es.uclm.esi.iso2</groupId>
    <artifactId>proyecto-iso2-grupoX</artifactId> <!-- Cambiar por vuestro grupo -->
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Proyecto Multimódulo ISO2</name>

    <!-- Aquí iréis añadiendo los módulos a medida que los creéis en las iteraciones -->
    <modules>
        <!-- <module>modulo-gestion-citas</module> --> 
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>
